### ISSUE TITLE
Review Ticket: Getting Started With MySQL Using R

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/ph-submissions#153]
The Programming Historian has received the following tutorial on 'Getting Started With MySQL Using R' by @jeffblackadar. This lesson is now under review and can be read at:

https://programminghistorian.github.io/ph-submissions/lessons/getting-started-with-mysql-using-r

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have read through the lesson and provided feedback, to which the author has responded. I'll now solicit two reviewers to comment on this page.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to ombudsperson @ianmilligan1 if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan or Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by amandavisconti** [comment]
@jeffblackadar I've tweeted an invitation to lesson reviewers, and will also email some possible reviewers on Monday 3/5. Hoping to find two people who can, within two weeks, work through your lesson and provide any feedback here. Then, you and I will discuss their feedback, and if we agree the lesson seems ready, you'd make any last changes and we'd be ready to publish.

I'll keep you updated as we ID reviewers—let me know if you have any questions or could use an update? Thanks so much for writing this lesson—happy to see ProgHist cover these topics, and will definitely be pointing others at your lesson!

**Comment by jeffblackadar** [comment]
Many thanks @amandavisconti!  I will stay tuned for feedback.
Jeff

**Comment by amandavisconti** [comment]
Jesse Sadler (@jessesadler) and Simon Appleford (@apl4d) have generously agreed to serve as formal reviewers—thanks! I've emailed them to ask for their GitHub handles and set a deadline for their reviews to the end of the day on Monday, March 19th (two weeks from today).

Members of the wider community are also invited to offer constructive feedback here on this GitHub ticket, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (https://programminghistorian.org/editor-guidelines#anti-harassment-policy). Unlike other peer review processes, we're focused on maximizing the potential of each lesson through kind and generous discussion. (**We do not solicit reviews to judge whether a tutorial is “good enough” to be published.**) Our guidelines explains what to comment on as a reviewer, and our philosophy about the spirit in which you provide feedback.

Formal reviewers will be credited for their work at the top of the published lesson page, and informal reviewers may be credited elsewhere in the lesson.

We will ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

Thanks again to Jeff for creating this lesson, and to Jesse and Simon for agreeing to formally review!

**Comment by apl4d** [comment]
General Comments:
Thanks @amandavisconti for the opportunity to review @jeffblackadar's useful and thorough tutorial. Overall, I liked it a lot and think that it will be of interest to a growing number of scholars. Although there are some repetitive sections, especially with duplicated code, I found it to be well-written and easy to follow. It eased the reader through a relatively steep learning curve to produce an exploratory visualization of the provided dataset. There were a couple of places (outlined on a paragraph level below) where there were some inconsistencies between what was described and my experience, but overall nothing major.

There is some inconsistency in the assumed technical ability of the user. At times, relatively basic concepts are explained in surprising detail (for example, the composition of a database table is described and a screenshot showing the downloaded installer file in OSX provided). Elsewhere, more complicated and abstract ideas, especially some of the code in R, is glossed over without much explanation. Some of this might be the result of some of the table formatting issues that recur in the second half of the lesson, but there is clearly some inconsistency in what level of expertise this is aimed at. With the lesson identified as being of "Medium" difficulty, I would suggest editing down some of these more basic explanations and add more detail to help explain the conceptual framework of what the code is doing, which will make it easier to adapt it to other projects. As a minimum, I'd suggest a brief introduction to each main section that explains what we'll be doing and why. 

It was also a little confusing that the opening vignette (nineteenth century Canadian newspapers) and sample data (WW1-era German submarines and gardens!) have little relation to each other. It would have been helpful to have a brief summary of what we are ultimately working towards, perhaps in paragraph 18 when the source of the sample data is identified as coming from the Welsh Newspapers Online archive. This is especially important because the stated motivating problem (preparing a structured dataset for NLP that can easily be queried online) is not what we necessarily produce at the end of the lesson. I think some explanation of the actual data (and problem we're solving) that we're using will help show a less technical user why we might want to apply these techniques to other projects.

Specific Issues (most of these are stylistic and grammar-related, but there are some more substantive suggestions as well):
p. 1 - A little more explication of why you might want to "store data from your digital history projects in a structured and permanent place" would be helpful here.
p. 2 - "use the data for things like sorted lists and calculations" Beyond the "nice looking graph" that is produced, the lesson doesn't actually tell us how to do this. A short section towards the end that describes how to use R to extract some of this summary data into a table might be helpful in this regard.
p. 3 - The lesson makes no other reference to how these techniques can be transferred to another programming language.
p. 4 - "a database system called MySQL and it works on Windows, Mac and Linux" replace "and it" with "which"
p. 5 - The lesson is described as medium difficulty, which seems appropriate. Make sure header is changed from "low" to "medium"
p. 14 - "This lesson is an introduction to using the MySQL relational database with R in a similar way I used to create the finding aid I worked on." This sentence could be reworked for clarity and to establish that we'll be working with a very different dataset to the one previously described. I also think this is an opportunity to explain exactly what we'll produce at the end of the lesson.
p. 16 - Of the three items on this list, I think the only one that the lesson specifically demonstrates is how to handle large amounts of data. It might be outside the scope of this lesson, but I would suggest as a minimum adding a "next steps" section that points to resources to help put the database online and make it searchable with a form and to demonstrate how to resume an interrupted process with R
p. 19 - At some point in the lesson, the author should make explicit which versions of the various software and packages are being used. He should also call out the RMySQL package and version number in this section.
p. 19 - "packages" not "packgages"
p. 21 - Consider merging this paragraph with #22 since Dewar's lesson provides a step-by-step guide to installing R
p. 24 - delete "so" from the first sentence.
p. 31 - Is the parenthetical reference to "Installation tips for a Mac follows this section" necessary?
p. 32-45 - note that I don't have access to a PC to evaluate these instructions beyond grammar and clarity
p. 32 - These installation tips would be clearer as a numbered list, especially since the step in paragraph 44 prompts you to refer to something "you wrote down in the step above" (the "step above" being four paragraphs earlier)
p. 32 - fix the italics
p. 40 - "root password" not "password for root"
p. 41 - Could you further explicate, in just a couple of words, what a Windows Service is?
p. 46-54 - again, I think a numbered list would be clearer here
p. 47 - is this screenshot of the package installer file needed?
p. 52 - It might be clearer to explicate in the instructions that you should replace the text "the_root_password_you_wrote_down_above" and "your_new_password_you_just_wrote_down" with the relevant passwords.
p. 52#2 - As written I get an ERROR 1064 (syntax). I believe the fix is to delete "mysql> " from the text to be entered
p. 52#3 - I'm not sure what is meant by "repeat 3." I think the point here is that you might need to go back to system preferences and restart the MySQL Server? But as written the user might think that they have to go back through the process of resetting the root password.
p. 56 - This description of the individual components of a table seems incongruous with the technical expertise assumed elsewhere. As a minimum, rewrite the fourth sentence for clarity. I think the example data is throwing me, so perhaps just remove it: "An example record of basic contact information might contain separate fields for "name", "phone number", and "e-mail address"."
p. 57 - Warn the user that they will be prompted for the root password that they created in previous steps (at least on the Mac)
p. 57 - My version of Workbench automatically opened a new query tab. I therefore wonder if the final instruction on this line is redundant.
p. 64 - an annotated screenshot of the Add Table interface would be really helpful here. Also, I think more detailed instructions on how to add columns through the interface is needed.
p. 65 - When I add the columns using the steps outlined in paragraph 64, the default generated code doesn't match what is provided here. Specifically, it reads:
```
CREATE TABLE `newspaper_search_results`.`tbl_newspaper_search_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `story_title` VARCHAR(99) NULL,
  `story_date_published` DATETIME NULL,
  `story_url` VARCHAR(99) NULL,
  `search_term_used` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));
```
This difference might be confusing/alarming, so might be worth highlighting (note especially the lack of "DEFAULT" throughout)
p. 69#6 - MySQL Workbench opened with a default window that wasn't wide enough to display the "Add Entry" button; since there is no horizontal scroll bar provided on this window I'd recommend warning users about this issue since it took me a couple of minutes to work out what was going on
p. 69#7 - Add "Click OK" at the end of the instruction
p. 71 - OK. I guess this is referring to the issues I had above in 69#6. I think this warning should be moved so that it appears sooner; I didn't think to look under the screenshot for help! Also, the instruction in the last sentence of this paragraph should be clearer
p. 71 - the second line of code had no effect when I executed it (I'm not familiar enough with MySQL syntax to troubleshoot, but I did doublecheck all spellings, etc)
p. 74 - Is there anywhere special the file should be saved in relation to the workspace?
p. 79 - The phrase "something like" seems ambiguous
p. 79 - Need to be consistent as to whether or not we're including the ">" symbol in code. I'm guessing it shouldn't be here
p. 80 - The formatting of this section is very confusing. It looks like the instructions are formatted in a two column table? Meanwhile, the code should appear after the instruction "save it" and shouldn't duplicate the `library(RMySQL)` command. I would also add a warning that if you don't select all the text before pressing the Run button that it won't work properly (Not that I spent several minutes troubleshooting this!)
p. 81 - I get the following result when running the code:
```
> dbListTables(storiesDb)
[1] "tbl_newspaper_search_results"
> dbDisconnect(storiesDb)
[1] TRUE
```
p. 84 - Instead of Nano I'd suggest calling out TextEdit, which is the default Mac text editor
p. 84 - add "and" before "paste in the items belows"
p. 89#2 - "Highlight" not "Highligh"
p. 91 - Given most users will likely just copy and paste this long section of code, I'd remind them this first time to change the path to the settings file
p. 96 - I found the choice of "consolidate" here confusing as I initially expected another summary of the previous set of actions rather than a new set of instructions. I'd suggest clarifying this.
p. 97 - I'd recommend further clarification of what this step is actually doing. As written I was expecting to be bulk adding records to the database, but that isn't what the code does
p. 97 - "convert the string value" not "convert the sting value"
p. 99 - Can you introduce the goals of this section?
p. 109 - Can you describe what is in each of the csv files?
p. 111 - Could you reference that the sampleData frame should contain "1242 obs. of 4 variables" so a user can verify this worked properly?
p. 114 - again, the formatting seems to be off. It isn't clear what "|Function|Meaning|...etc.|" is referring to. I think this is meant to be a table to explain what the function does?
p. 117 - Can you call out that an explanation of the program follows in the last section?
p. 120 - again, I think this is meant to be a table, but the formatting is broken
p. 123 - "Below" not "pBelow"

**Comment by jeffblackadar** [comment]
Hi Simon
Thank you for this review and feedback. I'm on the road driving and so I
will go through this thoroughly when I am sitting in one place.
Jeff

**Comment by jessesadler** [comment]
General comments: Thanks to @amandavisconti for the opportunity to review @jeffblackadar's thoughtful tutorial on MySQL and R. I came in with no experience with MySQL and was able to get a start on it with this tutorial. My main thoughts on the tutorial is that it could use some more background information about SQL, MySQL, and Workbench. I looked around a bit and found the resources on MySQL and Workbench somewhat off-putting. The importance of MySQL seems to be assumed. The documentation is certainly not intended for individual researchers. A short introduction to the use of MySQL in research would be useful. The payoff is also not really clear. I am not sold on why I should bother with MySQL instead of just using R.

I had a lot of trouble installing MySQL, resetting the password, and linking to Workbench. It may be helpful to more fully distinguish between what code is shell prompts and what are MySQL commands that must end with `;`. The documentation for MySQL was totally unhelpful when I ran into a problem, so I think you need to be very clear here, because if you run into a problem answers are not easy to find.

The R code could be formatted more clearly and more consistently. I noted some specific instances below. Working with the RMySQL package is very different from a lot of R code, so I think there could be more background on how the package interfaces with MySQL in R.

The lesson as a whole is very ambitious, at least I found it ambitious. I think that overall the lesson does a good job leading you through a fairly daunting task.

- Flow
	- The sections are very broken up, and so I got a little lost. For instance, I am not sure that there is a need for a whole section on inputting a row or data, or at least in saying "this section of the lesson we’ll..." (p87), especially since this language is repeated in the next section.
	- Feels like a long time before we get to real data on p108 and then the discussion of working with real data is over very quickly.

- p1–2: The first paragraph is vague. One issue that I always struggled with before getting into digital history is what it means to store data in a database. Can you give some concrete examples or give a short discussion of the benefits of using MySQL. You do go into this in the Introduction, but there could be more explanation here to bring people in.
- Introduction
	- Use of the conditional and past tense in the Introduction is a bit distracting.
	- The example of the Shawville Equity newspaper could be made less personal. The section reads as a history of decisions. The value that using MySQL has for historians is not as clear as it could be.
	- More emphasis on value of MySQL in dealing with large amounts of data. Sell me on the use of MySQL.
- Required Software
	- More background to MySQL would be helpful. Why SQL and why MySQL. The website for MySQL states "MySQL Community Edition is a freely downloadable version of the world's most popular open source database that is supported by an active community of open source developers and enthusiasts." Something like this would be useful. I want to know why I am downloading a piece of software and why it is the best software to download and use.
	- The same goes for Workbench. Do you need Workbench to use MySQL? Why is it useful to use Workbench?
- Installation
	- The installation process did not work for me the first time. When I typed in my password in p52#1 I got "ERROR 1045 (28000): Access denied for user 'root'@'localhost'". I could not reset my password, nor could I access the local server with Workbench. I eventually gave up and uninstalled and then reinstalled MySQL. The second time through the process worked, though I had to use quotations around my temporary password.
	- It also took me a while to get that `;` is used to end prompts within MySQL, which caused some pain.
	- I found this StackOverflow answer helpful: https://stackoverflow.com/a/37524283
- Create a database
	- p56: This explanation is overly written and makes a table seem more complex than it is.
	- p58: Introduce that these set of commands will create a new database called "newspaper_search_results". Step 4 is not a step but a result that is the same as 3.
	- p58#2: would be helpful to introduce the keyboard command to run the query. On Mac it is `command + return`.
	- p63: I think it would be preferable to describe what the command does before giving the command, so this paragraph could go before p61.
	- p67: Explanation of what users are and why you might want to deal with privileges could be more fully explained.
- R Program
	- I am not sure that it is necessary to repeat the R script over and over.
	- This is a small thing, but calling the R script a program seems odd to me. This could also lead to confusion, for instance in p93. I think that something like execute the above lines of code would be clearer.
	- The R code would be easier to read if there are spaces around the assignment operator: `localuserpassword <- "SomethingDifficult"`
	- It would also improve readability of the R code to reflow the comments and code to keep it at a maximum of 80 characters. The `storiesDb` code could be broken up at each comma for readability.
- Querying data in the table with SQL
	- A little more information about why we should do these commands would be useful.
- Storing data in a table with SQL using R
	- I would prefer to have the explanation in p92 above the code so that people do not just copy and paste without knowing what is going on.
	- It would be useful to explain what is going on with the command discussed in p92#1 and p92#2 in a more general sense. That you are writing queries as a character object and using `dbSendQuery()` to perform that query.
	- Clarify what is done in the code for p97
	- Simpler to just create the date directly: `as.Date("1916-05-21")`
	- There is an unnecessary space in `print(query)`
- Storing a CSV
	- p112: should be "story_title, story_date_published, story_url and search_term_used"
	- p113: First sentence is a bit confusing because of the multiple uses of sample data. Maybe call the data.frame gardenData or something different than sampleData.
	- In the script for p115 I think that the two different data frames of sample data should have different names so that the first is not overwritten. This could avoid confusion.
- Selecting data from a table with SQL using R
	- The code in this section is fairly complex with very little explanation. More significantly though, I got somewhat lost at this point as to why I am doing what I am doing. I can make my way through the code and figure it out, but this last section could use some framing.

**Comment by jeffblackadar** [comment]
Hi Jesse
Thanks for your feedback. I'll go through this when I am back from being on
the road.
Jeff

**Comment by amandavisconti** [comment]
Thanks @apl4d @jessesadler for your reviews! I'll read through these and work with @jeffblackadar for the next stage of the process. @jeffblackadar, I will be in touch by email by the end of the day Wednesday (2/21) if not earlier so we can discuss next steps. Thanks again for authoring this, and for your willingness to review in public!

**Comment by amandavisconti** [comment]
In order to keep the process moving, we've now closed the period for open review and will not be incorporating reviews/feedback from folks other than the two formal reviews above into the current publication process.

**Comment by amandavisconti** [comment]
I've condensed Simon and Jesse's reviews, with some points of my own thrown in, and tried to put them all in chronological order. @jeffblackadar I formatted these as checkboxes in case that would help you work through them, and am sending you an email with details as well:

- [ ] "Getting Start with MySQL" section (p. 7 on): “It was a little confusing that the opening vignette (nineteenth century Canadian newspapers) and sample data (WW1-era German submarines and gardens!) have little relation to each other. It would have been helpful to have a brief summary of what we are ultimately working towards, perhaps in paragraph 18 when the source of the sample data is identified as coming from the Welsh Newspapers Online archive. This is especially important because the stated motivating problem (preparing a structured dataset for NLP that can easily be queried online) is not what we necessarily produce at the end of the lesson. I think some explanation of the actual data (and problem we're solving) that we're using will help show a less technical user why we might want to apply these techniques to other projects.”
- [ ] My main thoughts on the tutorial is that it could use some more background information about SQL, MySQL, and Workbench. I looked around a bit and found the resources on MySQL and Workbench somewhat off-putting. The importance of MySQL seems to be assumed. The documentation is certainly not intended for individual researchers. A short introduction to the use of MySQL in research would be useful. The payoff is also not really clear. I am not sold on why I should bother with MySQL instead of just using R.
- [ ] I had a lot of trouble installing MySQL, resetting the password, and linking to Workbench. It may be helpful to more fully distinguish between what code is shell prompts and what are MySQL commands that must end with `;`. The documentation for MySQL was totally unhelpful when I ran into a problem, so I think you need to be very clear here, because if you run into a problem answers are not easy to find.
- [ ] p. 1 - A little more explication of why you might want to "store data from your digital history projects in a structured and permanent place" would be helpful here.
- [ ] p. 2 - "use the data for things like sorted lists and calculations" Beyond the "nice looking graph" that is produced, the lesson doesn't actually tell us how to do this. A short section towards the end that describes how to use R to extract some of this summary data into a table might be helpful in this regard. [Amanda: alternatively, linking readers to 1-2 resources that show them how to accomplish sorted lists/calculations would be a nice touch]
- [ ] p1–2: The first paragraph is vague. One issue that I always struggled with before getting into digital history is what it means to store data in a database. Can you give some concrete examples or give a short discussion of the benefits of using MySQL. You do go into this in the Introduction, but there could be more explanation here to bring people in.
- [ ] p. 4 - "a database system called MySQL and it works on Windows, Mac and Linux" replace "and it" with "which"
- [ ] p. 5 – remove “Some knowledge of the R language” from the sentence? I don’t remember any R but was able to complete the lesson.
- [ ] p. 5 - The lesson is described as medium difficulty, which seems appropriate. Make sure header is changed from "low" to "medium"
- [ ] Intro section: Use of the conditional and past tense in the Introduction is a bit distracting.
- [ ] Intro section: The example of the Shawville Equity newspaper could be made less personal. The section reads as a history of decisions. The value that using MySQL has for historians is not as clear as it could be.
- [ ] Intro section: More emphasis on value of MySQL in dealing with large amounts of data. Sell me on the use of MySQL.
- [ ] p. 14 - "This lesson is an introduction to using the MySQL relational database with R in a similar way I used to create the finding aid I worked on." This sentence could be reworked for clarity and to establish that we'll be working with a very different dataset to the one previously described. I also think this is an opportunity to explain exactly what we'll produce at the end of the lesson.
- [ ] p. 16 - Of the three items on this list, I think the only one that the lesson specifically demonstrates is how to handle large amounts of data. It might be outside the scope of this lesson, but I would suggest as a minimum adding a "next steps" section that points to resources to help put the database online and make it searchable with a form and to demonstrate how to resume an interrupted process with R
- [ ] Required Software Section (p. 19-55): More background to MySQL would be helpful. Why SQL and why MySQL. The website for MySQL states "MySQL Community Edition is a freely downloadable version of the world's most popular open source database that is supported by an active community of open source developers and enthusiasts." Something like this would be useful. I want to know why I am downloading a piece of software and why it is the best software to download and use.
- [ ] Required Software Section (p. 19-55): The same goes for Workbench. Do you need Workbench to use MySQL? Why is it useful to use Workbench?
- [ ] Installation: The installation process did not work for me the first time. When I typed in my password in p52#1 I got "ERROR 1045 (28000): Access denied for user 'root'@'localhost'". I could not reset my password, nor could I access the local server with Workbench. I eventually gave up and uninstalled and then reinstalled MySQL. The second time through the process worked, though I had to use quotations around my temporary password.
- [ ] Installation: It also took me a while to get that ; is used to end prompts within MySQL, which caused some pain.
- [ ] Installation: I found this StackOverflow answer helpful: https://stackoverflow.com/a/37524283
- [ ] p. 19 - At some point in the lesson, the author should make explicit which versions of the various software and packages are being used. He should also call out the RMySQL package and version number in this section.
- [ ] p. 19 - "packages" not "packgages"
- [ ] p. 21 - Consider merging this paragraph with #22 since Dewar's lesson provides a step-by-step guide to installing R
- [ ] p. 24 - delete "so" from the first sentence.
- [ ] p. 31 - Remove parenthetical reference to "Installation tips for a Mac follows this section", since it follows immediately after
- [ ] p. 32-45 Neither Simon nor Amanda had PC access, so could not evaluate these except for grammar/clarity; check whether Jesse was able to use these on a PC?
- [ ] p. 32 - These installation tips would be clearer as a numbered list, especially since the step in paragraph 44 prompts you to refer to something "you wrote down in the step above" (the "step above" being four paragraphs earlier)
- [ ] p. 32 - fix the italics
- [ ] p. 40 - "root password" not "password for root"
- [ ] p. 41 - Could you further explicate, in just a couple of words, what a Windows Service is?
- [ ] p. 46-54 - again, I think a numbered list would be clearer here
- [ ] p. 47 screenshot (http://jeffblackadar.ca/getting-started-with-mysql/getting-started-with-mysql-17.png) unnecessary?
- [ ] p. 52 - It might be clearer to explicate in the instructions that you should replace the text "the_root_password_you_wrote_down_above" and "your_new_password_you_just_wrote_down" with the relevant passwords.
- [ ] p. 52#2 - As written I get an ERROR 1064 (syntax). I believe the fix is to delete "mysql> " from the text to be entered
- [ ] p. 52#3 - I'm not sure what is meant by "repeat 3." I think the point here is that you might need to go back to system preferences and restart the MySQL Server? But as written the user might think that they have to go back through the process of resetting the root password.
- [ ] p. 56 - This description of the individual components of a table seems incongruous with the technical expertise assumed elsewhere. As a minimum, rewrite the fourth sentence for clarity. I think the example data is throwing me, so perhaps just remove it: "An example record of basic contact information might contain separate fields for "name", "phone number", and "e-mail address"."
- [ ] p. 57 - Warn the user that they will be prompted for the root password that they created in previous steps (at least on the Mac)
- [ ] p. 57 – edit to say “On some Macs, a Query Tab will already be open; if it is not, open a Query Tab by doing File > New Query Tab”. (Simon had a query tab already open for him on a Mac; I didn’t—seems good to cover both possibilities)
- [ ] p58: Introduce that these set of commands will create a new database called "newspaper_search_results". Step 4 is not a step but a result that is the same as 3.
- [ ] p58#2: would be helpful to introduce the keyboard command to run the query. On Mac it is command + return.
- [ ] p63: I think it would be preferable to describe what the command does before giving the command, so this paragraph could go before p61.
- [ ] p. 64 - an annotated screenshot of the Add Table interface would be really helpful here. Also, I think more detailed instructions on how to add columns through the interface is needed.
- [ ] p. 65 - When I add the columns using the steps outlined in paragraph 64, the default generated code doesn't match what is provided here. Specifically, it reads:
  CREATE TABLE `newspaper_search_results`.`tbl_newspaper_search_results` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `story_title` VARCHAR(99) NULL,
    `story_date_published` DATETIME NULL,
    `story_url` VARCHAR(99) NULL,
    `search_term_used` VARCHAR(45) NULL,
    PRIMARY KEY (`id`));
This difference might be confusing/alarming, so might be worth highlighting (note especially the lack of "DEFAULT" throughout)
- [ ] p67: Explanation of what users are and why you might want to deal with privileges could be more fully explained.
- [ ] p. 69#6 - MySQL Workbench opened with a default window that wasn't wide enough to display the "Add Entry" button; since there is no horizontal scroll bar provided on this window I'd recommend warning users about this issue since it took me a couple of minutes to work out what was going on
- [ ] p. 69#7 - Add "Click OK" at the end of the instruction
- [ ] p. 71 - OK. I guess this is referring to the issues I had above in 69#6. I think this warning should be moved so that it appears sooner; I didn't think to look under the screenshot for help! Also, the instruction in the last sentence of this paragraph should be clearer
- [ ] p. 71 - the second line of code had no effect when I executed it (I'm not familiar enough with MySQL syntax to troubleshoot, but I did doublecheck all spellings, etc)
- [ ] Title before p. 72: This is a small thing, but calling the R script a program seems odd to me. This could also lead to confusion, for instance in p93. I think that something like execute the above lines of code would be clearer.
- [ ] p. 74 - Is there anywhere special the file should be saved in relation to the workspace?
- [ ] p. 79 - The phrase "something like" seems ambiguous
- [ ] p. 79 - Need to be consistent as to whether or not we're including the ">" symbol in code. I'm guessing it shouldn't be here
- [ ] p. 79 - The R code would be easier to read if there are spaces around the assignment operator: localuserpassword <- "SomethingDifficult"
- [ ] p 79 - It would also improve readability of the R code to reflow the comments and code to keep it at a maximum of 80 characters. The storiesDb code could be broken up at each comma for readability.
- [ ] p. 80 - The formatting of this section is very confusing. It looks like the instructions are formatted in a two column table? Meanwhile, the code should appear after the instruction "save it" and shouldn't duplicate the library(RMySQL) command. I would also add a warning that if you don't select all the text before pressing the Run button that it won't work properly (Not that I spent several minutes troubleshooting this!)
- [ ] p. 81 - I get the following result when running the code:
    > dbListTables(storiesDb)
    [1] "tbl_newspaper_search_results"
    > dbDisconnect(storiesDb)
    [1] TRUE
- [ ] p. 84 – In addition to notepad and nano, add TextEdit, which is the default Mac text editor?
- [ ] p. 84 - add "and" before "paste in the items belows"
- [ ] p. 87 - I would prefer to have the explanation in p92 above the code so that people do not just copy and paste without knowing what is going on.
- [ ] p. 89#2 - "Highlight" not "Highligh"
- [ ] p. 91 - Given most users will likely just copy and paste this long section of code, I'd remind them this first time to change the path to the settings file
- [ ] p. 96 - I found the choice of "consolidate" here confusing as I initially expected another summary of the previous set of actions rather than a new set of instructions. I'd suggest clarifying this.
- [ ] p. 97 - I'd recommend further clarification of what this step is actually doing. As written I was expecting to be bulk adding records to the database, but that isn't what the code does
- [ ] It would be useful to explain what is going on with the command discussed in p92#1 and p92#2 in a more general sense. That you are writing queries as a character object and using dbSendQuery() to perform that query.
- [ ] Clarify what is done in the code for p97
- [ ] Simpler to just create the date directly: as.Date("1916-05-21")
- [ ] There is an unnecessary space in print(query)
- [ ] p. 97 - "convert the string value" not "convert the sting value"
- [ ] p. 99 - Can you introduce the goals of this section?
- [ ] p. 109 - Can you describe what is in each of the csv files?
- [ ] p. 111 - Could you reference that the sampleData frame should contain "1242 obs. of 4 variables" so a user can verify this worked properly?
- [ ] p112: should be "story_title, story_date_published, story_url and search_term_used"
- [ ] p113: First sentence is a bit confusing because of the multiple uses of sample data. Maybe call the data.frame gardenData or something different than sampleData.
- [ ] In the script for p115 I think that the two different data frames of sample data should have different names so that the first is not overwritten. This could avoid confusion.
- [ ] p. 114 - again, the formatting seems to be off. It isn't clear what "|Function|Meaning|...etc.|" is referring to. I think this is meant to be a table to explain what the function does?
- [ ] p. 117 - Can you call out that an explanation of the program follows in the last section? 
- [ ] p. 117 on: The code in this section is fairly complex with very little explanation. More significantly though, I got somewhat lost at this point as to why I am doing what I am doing. I can make my way through the code and figure it out, but this last section could use some framing.
- [ ] p. 120 - again, I think this is meant to be a table, but the formatting is broken
- [ ] p. 123 - "Below" not "pBelow"

**Comment by jeffblackadar** [comment]
Many Thanks Amanda, I will work on this.  I appreciate all of the
consolidation you did.
Jeff

**Comment by amandavisconti** [comment]
I neglected to record here the deadline we agreed to shoot for in our 3/21 email; it's 4/19. @jeffblackadar does that still work for you?

**Comment by jeffblackadar** [comment]
May I have until 22 April to finish? I am working days and have more than a
couple evenings of work left.
Jeff

On Tuesday, April 17, 2018, Amanda Visconti <notifications@github.com>
wrote:
> I neglected to record here the deadline we agreed to shoot for in our
3/21 email; it's 4/19. @jeffblackadar does that still work for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/Et8PMMtnySPz36aupxEpJD3n3IVB93BRMgus1ybP9Ahq_UymjxCcd-NE4W_bqlDrXAJ3CvI6b1mGYz45OfrQ15sHwCovm1h-sOaNE4LNMyvlLmg-cLpZ2Mk1APUbfA7ZttSOMfT84nAx3xKizvcpARhRZ3VRLw=s0-d-e1-ft#https://github.com/notifications/beacon/AclCTxEZYbsrJ1eaaGdlnZyyTArqSFYlks5tpihSgaJpZM4Savl9.gif>

**Comment by amandavisconti** [comment]
Sure, that sounds fine!

**Comment by jeffblackadar** [comment]
Hi Amanda
I have completed the edits from the review.  Thanks for collecting and 
editing these it was much easier to work through them that way.  
Responses are attached.
Best,
Jeff

**Comment by amandavisconti** [comment]
Excellent, @jeffblackadar! Thank you. My next steps are below. I'm going to try to complete these this week; I'll update you on Friday (2/27) with a specific date I think the lesson will be ready by, if I'll need a couple more days to complete working through these.

- [x] Check formatting of rendered lesson
- [x] Work through "[Technical Processes of Review - Editorial Checklist](https://programminghistorian.org/editor-guidelines#technical-processes-of-review---editorial-checklist)" (tasks like moving lesson images to the right folder) = moved remaining tasks to below
- [x] Work through "[Acceptance and Publication - Editorial Checklist](https://programminghistorian.org/editor-guidelines#acceptance-and-publication---editorial-checklist)" (tasks like moving the lesson to the main PH site repo, filling out author bio)

- [x] host data & images in ph/jekyll repo
- [x] placed in a subdirectory within the images directory. The subdirectory should be named using the same URL slug used to name the lesson. Make sure the images are in web-friendly formats such as PNG or JPEG and sized appropriately (both in terms of pixels and bytes)
- [x] data in assets/lesson-slug/data.csv
- [x] {% include figure.html filename="IMAGE-FILENAME" caption="Caption to image" %} for all images

- [x] Push finalized lesson+associated files to ph/jekyll repo
- [x] Check if Travis found errors
- [x] Check lesson (especially images/captions) appears correctly on ph.org
- [x] Move ph-submission lesson+files to lessons/published and images/published
- [x] Ask Jeff for 1-2 sentence author bio and add to ph_authors
- [x] Add info to Twitterbot spreadsheet (early in week, #ICYMI, link to lesson; didn't have access so asked Brandon to add, thanks Brandon!)
- [x] Tweet from personal & PH Twitters (scheduled)

**Comment by amandavisconti** [comment]
@jeffblackadar Hi, Jeff! I will need a couple more days to finish up our work on the lesson; I'm planning to have this done by the end of day Wednesday (5/2). Thanks for your patience!

edit: Wednesday is actually _5/3_!
second edit: um, no it isn't

**Comment by amandavisconti** [comment]
The lesson is ready and passed all automated checks—just waiting on another editor to merge the pull request, and the lesson will be live! Thanks @jeffblackadar for authoring, and @jessesadler @apl4d for reviewing!
